In [31]:
#@title #####**Useful Functions**

# df1.isnull().sum()
# df1['Brand'].unique()
# df1.dtypes
# df['Price ($)'].head(237)
# df.head()

***Mobile price dataset*** is given and we need to train the model and make ready for new testing.

In [32]:
#@title #####**Loading the dataset**
import pandas as pd
import matplotlib.pyplot as plt

df1=pd.read_csv('price.csv')
df1.head()

,Brand,Model,Storage,RAM,Screen Size (inches),Camera (MP),Battery Capacity (mAh),Price ($)
0,Apple,iPhone 13 Pro,128 GB,6 GB,6.1,12 + 12 + 12,3095,999
1,Samsung,Galaxy S21 Ultra,256 GB,12 GB,6.8,108 + 10 + 10 + 12,5000,1199
2,OnePlus,9 Pro,128 GB,8 GB,6.7,48 + 50 + 8 + 2,4500,899
3,Xiaomi,Redmi Note 10 Pro,128 GB,6 GB,6.67,64 + 8 + 5 + 2,5020,279
4,Google,Pixel 6,128 GB,8 GB,6.4,50 + 12.2,4614,799

In [33]:
#@title #####**Preprocessing with the dataset**

df=df1.drop(['Brand','Model','Camera (MP)'],axis=1)
df['Storage'] = df['Storage'].str.replace("GB", "")
df['RAM'] = df['RAM'].str.replace("GB", "")
df['Price ($)'] = df['Price ($)'].str.replace("$", "")
# df['RAM'] = df['RAM'].astype('float')

for col in df.columns:
 df[col] = pd.to_numeric(df[col], errors='coerce')
 df[col]=df[col].astype(float)


df['Price ($)']=df['Price ($)'].fillna(df['Price ($)'].mean())
df['Screen Size (inches)']=df['Screen Size (inches)'].fillna(df['Screen Size (inches)'].mean())


df.shape
# df.isnull().sum()

<ipython-input-33-91338cd39715>:6: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  df['Price ($)'] = df['Price ($)'].str.replace("$", "")

(407, 5)

In [34]:
#@title #####**Break dataset into training and testing data**

X=df.iloc[:,:-1]
Y=df.iloc[:,-1:]

# 407 ka (50%=204,60%=244,70%=285,80%=325)
n=325
xtrain=X[:n]
ytrain1=Y[:n]
xtest=X[n:]
ytest1=Y[n:]

ytrain=ytrain1.values.ravel();
ytest=ytest1.values.ravel();
print(len(xtrain),len(xtest))
df.head()


# len(df['Price ($)'].unique())

325 82

   Storage   RAM  Screen Size (inches)  Battery Capacity (mAh)  Price ($)
0    128.0   6.0                  6.10                  3095.0      999.0
1    256.0  12.0                  6.80                  5000.0     1199.0
2    128.0   8.0                  6.70                  4500.0      899.0
3    128.0   6.0                  6.67                  5020.0      279.0
4    128.0   8.0                  6.40                  4614.0      799.0

In [35]:
#@title #####**Using LinearRegression model**

from sklearn.linear_model import LinearRegression
model =  LinearRegression()
model.fit(xtrain,ytrain)
print("Accuracy ",model.score(xtest, ytest))

Accuracy  0.5421592086063023

In [36]:
#@title #####**Comparing both prediction and test label dataset**
p=model.predict(xtest).astype('int')
print("prediction",p)
print("\nytest",ytest)
# model.predict([[128,6,6.2,3100]])

prediction [ 706  416  506  144  435  771  345  529  538   97  941  301  318  847
  312  364  415  810  431  841  511  391  435  312  166  521  734  466
  488  533  413  312  506  178  312  431 1389  307  801  178  301  874
 1492  364  954  363  483  183  872  418  940  812  431  112  682  143
  312  458  301  651  314  364  544  560  178  529  521  524  483  166
  415  557  178  431  548  445  530  513  478  544  544  435]

ytest [ 599.  699.  419.  199.  399. 1099.  249.  699.  399.  449.  799.  179.
  279. 1099.  279.  249.  399.  999.  699.  699.  249.  279.  699.  249.
  229.  329.  999.  399.  499.  449.  499.  179.  399.  199.  199.  449.
 1399. 1099.  999.  179.  179.  799. 1399.  229.  899.  199.  729.  229.
 1999.  599.  799.  999.  699.  139.  449.  119.  279.  299.  199.  999.
  329.  329.  799.  749.  199.  699.  349. 1199.  749.  199.  299.  599.
  149.  449.  319.  329.  329. 1049.  349. 1099.  429.  649.]