In [ ]:
#@title #####**Useful Functions**
# titanic.isnull().values.any()   # In entire dataset contains NAN value or not
# titanic.isnull().sum()  #column wise NAN value showing
# len(titanic['embark_town'].unique())
# titanic['embark_town'].unique()     no. of unique value in that column
# sns.get_dataset_names() #show all dataset  available
# titanic.isnull().values.any()   # In entire dataset contains NAN value or not

**Titanic dataset:** a dataset curated on the basis of the passengers on titanic, like their age, class, gender, etc to predict if they would have survived or not.

In [ ]:
#@title #####**Loading the dataset**

import pandas as pd
import seaborn as sns   #seaborn provides function that help to quick access to small dataset
titanic=sns.load_dataset('titanic') #loaded titanic dataset
titanic.isnull().sum()  #column wise NAN value showing(show kiya gya)

In [ ]:
#@title #####**Deal with missing value columns of the dataset**
# removing the missing data (remove kiya gya)
titanic.dropna(subset=['embark_town','embarked'],axis=0,inplace=True)
titanic.age=titanic.age.interpolate()
titanic=titanic.drop(['deck'],axis=1)
titanic.isnull().sum()

In [ ]:
#@title #####**Showing the dataset**
titanic.head()  # showing the titanic dataset

In [ ]:
#@title #####**Converting columns non numerical into numerical float value**
titanic['class']=titanic['class'].map({'First':100, 'Second':200, 'Third':300}).astype('float') #numeric category wale ko numerical value se
titanic['sex']=titanic['sex'].map({'male':True, 'female':False})  # booloen category wale ko boolean category me replace kiya gya
titanic.head()

In [ ]:
#@title #####**Deal with dummy variables**
#multiple category wale columns ko new column se replce kar diya gya jise dummies variables kaha jata hai.
port1=pd.get_dummies(titanic['embarked'],prefix='emb')
port3=pd.get_dummies(titanic['who'],prefix='wh')
port4=pd.get_dummies(titanic['embark_town'],prefix='etown')

titanic=titanic.join(port1)
titanic=titanic.join(port3)
titanic=titanic.join(port4)

titanic=titanic.drop(['embarked','alive','who','embark_town','pclass','parch','etown_Southampton','wh_woman','emb_S'],axis=1)
# titanic.isnull().sum()

titanic.head()

In [ ]:
#@title #####**Applying the Normalization**
import numpy as np

nc=titanic.select_dtypes(include=np.number)
nc1=nc.columns
t=titanic[nc1]
m=titanic[nc1].min()
M=titanic[nc1].max()
# using min-max scaling
titanic[nc1]=(t-m)/(M-m)
titanic[nc1]

titanic.isnull().sum()
titanic.head()
nc1
# titanic['class'].unique()

In [ ]:
#@title #####**Sort and Print the dataset**
titanic1=titanic.sort_values('survived',ascending=True)
titanic1.head()

In [ ]:
#@title #####**Balancing the dataset**
from imblearn.under_sampling import RandomUnderSampler
from collections import Counter
xt=titanic.drop(['survived'],axis=1)
yt=titanic['survived']
print('Resampled dataset shape %s' % Counter(yt))
ros = RandomUnderSampler(random_state=42)
X_res, y_res = ros.fit_resample(xt, yt)
print('Resampled dataset shape %s' % Counter(y_res))

In [ ]:
#@title #####**Break entire dataset into training and testing data**
features_0=X_res[:340]
features_1=X_res[340:680]
labels_0=y_res[:340]
labels_1=y_res[340:680]

# 340 ka (50%= 170,60%= 204,70%= 238,80%= 272)
n=272
trainds_features_0=features_0[:n]
testds_features_0=features_0[n:]

trainds_features_1=features_1[:n]
testds_features_1=features_1[n:]

trainds_labels_0=labels_0[:n]
testds_labels_0=labels_0[n:]

trainds_labels_1=labels_1[:n]
testds_labels_1=labels_1[n:]


train_ds_x=pd.concat([trainds_features_0, trainds_features_1],ignore_index=True)
test_ds_x=pd.concat([testds_features_0, testds_features_1],ignore_index=True)
train_ds_y=pd.concat([trainds_labels_0, trainds_labels_1],ignore_index=True)
test_ds_y=pd.concat([testds_labels_0, testds_labels_1],ignore_index=True)



train_x=train_ds_x;
train_y=train_ds_y.values.ravel();
test_x=test_ds_x;
test_y=test_ds_y.values.ravel();
# trainds_features_1
print(len(test_x),len(train_x))

In [ ]:
#@title #####**Using SVM**
from sklearn.svm import SVC # "Support vector classifier"
model = SVC(kernel='linear')
model.fit(train_x, train_y)
predictions = model.predict(test_x)
# print("predictions",predictions)
# print("test_y",test_y)

In [ ]:
#@title #####**Accuracy of the model**
percentage = model.score(test_x, test_y)
print("percentage : ",percentage)